<?php
namespace Lewisliang82\UEditor\Ucloud;

global $SDK_VER;
global $UCLOUD_PROXY_SUFFIX;
global $UCLOUD_PUBLIC_KEY;
global $UCLOUD_PRIVATE_KEY;
global $UCLOUD_PUB_BUCKET;
global $UCLOUD_PRI_BUCKET;

$SDK_VER = '1.0.8';
$UCLOUD_PROXY_SUFFIX = '';
$UCLOUD_PUBLIC_KEY = '';
$UCLOUD_PRIVATE_KEY = '';
$UCLOUD_PUB_BUCKET = '';
$UCLOUD_PRI_BUCKET = '';
